language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - oraclejdk6
  - openjdk8
  - openjdk7
  - openjdk6

script:
  - cd jfuzzylite
  - mvn install

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: change
    on_failure: always
