language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

script:
  - cd jfuzzylite
  - if [ "$FL_BUILDER" = "mvn" ]; 
    then
    mvn install
    fi
  - if [ "$FL_BUILDER" = "ant" ]; 
    then
    ant -f build.xml
    fi

matrix:
  - FL_BUILDER="mvn"
  - FL_BUILDER="ant"
  
notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: change
    on_failure: always
