language: java
git:
  depth: 1
script:
  - cd jfuzzylite
  - if [ "$FL_BUILDER" = "mvn" ]; 
    then
    mvn install ;
    fi
  - if [ "$FL_BUILDER" = "ant" ]; 
    then
    ant -f build.xml ;
    fi
    
matrix:
  include:
    - jdk: openjdk7
      env: FL_BUILDER=mvn
    - jdk: openjdk7
      env: FL_BUILDER=ant

    - jdk: oraclejdk8
      env: FL_BUILDER=mvn
    - jdk: oraclejdk8
      env: FL_BUILDER=ant

    - jdk: oraclejdk9
      env: FL_BUILDER=mvn
    - jdk: oraclejdk9
      env: FL_BUILDER=ant

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
