language: java

script:
  - cd jfuzzylite
  - if [ "$FL_BUILDER" = "mvn" ]; 
    then
    mvn install ;
    fi
  - if [ "$FL_BUILDER" = "ant" ]; 
    then
    ant -f build.xml ;
    fi

env:
  matrix:
    - FL_BUILDER=mvn
    - FL_BUILDER=ant
    
matrix:
  include:
    - jdk: openjdk7
    - jdk: oraclejdk8
    - jdk: oraclejdk9

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
